[package]
name = "avdanos-research"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
futures = "0.3.30"
notify = "6.1.1"
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
